name: neom_frequencies
description: Frequencies Details for Open Neom.
version: 1.3.0-dev
homepage: https://github.com/Open-Neom/neom_frequencies

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core: ^1.4.1-dev
  neom_commons: ^1.4.1-dev

  # TRANSITIVE DEPENDENCIES FOR PUB.DEV PUBLISHING
  get: ^5.0.0-release-candidate-9.3.2
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
